import open from 'open';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { ReportData, OrganizationReport, ContributorScore } from '../reporting/types.js';

/**
 * Generate table rows for organization rankings
 */
function generateTableRows(orgs: OrganizationReport[]): string {
  return orgs
    .map(
      (org, i) => `
          <tr>
            <td class="rank">#${i + 1}</td>
            <td>${escapeHtml(org.name)}</td>
            <td class="score">${org.score.toFixed(1)}</td>
            <td>${org.contributorCount}</td>
            <td>${org.breakdown.commits}</td>
            <td>${org.breakdown.prsAuthored} / ${org.breakdown.prsReviewed}</td>
            <td>${org.breakdown.issuesAuthored} / ${org.breakdown.issuesCommented}</td>
          </tr>`
    )
    .join('');
}

/**
 * Generate section for unaffiliated contributors
 */
function generateUnknownSection(unknown: ContributorScore[]): string {
  const total = unknown.reduce((sum, c) => sum + c.score, 0);
  const topContributors = unknown.slice(0, 5).map((c) => c.username);

  return `
      <div class="unknown-section" style="margin-top: 2rem;">
        <h3>Unaffiliated Contributors</h3>
        <p>${unknown.length} contributor${unknown.length === 1 ? '' : 's'} with no detected organization (combined score: ${total.toFixed(1)})</p>
        ${topContributors.length > 0 ? `<p>Top: ${topContributors.map((u) => escapeHtml(u)).join(', ')}</p>` : ''}
      </div>`;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Generate a complete self-contained HTML report
 *
 * @param report - Report data to render
 * @returns Complete HTML document string
 */
export function generateHtmlReport(report: ReportData): string {
  const repoNames = report.repos.join(', ');
  const topOrgs = report.organizations.slice(0, 15);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GitSneak Report - ${escapeHtml(repoNames)}</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.0/dist/chart.umd.min.js"></script>
  <style>
    /* Embedded styles - modern, clean design */
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; }
    .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
    header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; border-radius: 8px; margin-bottom: 2rem; }
    h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
    .meta { opacity: 0.9; font-size: 0.9rem; }
    .card { background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); padding: 1.5rem; margin-bottom: 1.5rem; }
    .card h2 { font-size: 1.25rem; margin-bottom: 1rem; color: #444; }
    .chart-container { position: relative; height: 400px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f8f9fa; font-weight: 600; }
    tr:hover { background: #f8f9fa; }
    .rank { font-weight: 600; color: #667eea; }
    .score { font-weight: 600; }
    .unknown-section { opacity: 0.7; }
    .unknown-section h3 { font-size: 1rem; margin-bottom: 0.5rem; }
    .unknown-section th { background: #f0f0f0; }
    footer { text-align: center; padding: 1rem; color: #666; font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Organization Involvement Report</h1>
      <p class="meta">Repositories: ${escapeHtml(repoNames)}</p>
      <p class="meta">Generated: ${report.generatedAt.toLocaleString()}</p>
    </header>

    <div class="card">
      <h2>Top Organizations by Involvement Score</h2>
      <div class="chart-container">
        <canvas id="orgChart"></canvas>
      </div>
    </div>

    <div class="card">
      <h2>Organization Rankings</h2>
      <table>
        <thead>
          <tr>
            <th>Rank</th>
            <th>Organization</th>
            <th>Score</th>
            <th>Contributors</th>
            <th>Commits</th>
            <th>PRs (Authored/Reviewed)</th>
            <th>Issues (Authored/Comments)</th>
          </tr>
        </thead>
        <tbody>
          ${generateTableRows(report.organizations)}
        </tbody>
      </table>
      ${report.unknownContributors.length > 0 ? generateUnknownSection(report.unknownContributors) : ''}
    </div>

    <footer>
      Generated by GitSneak
    </footer>
  </div>

  <script>
    const ctx = document.getElementById('orgChart').getContext('2d');
    const topOrgs = ${JSON.stringify(topOrgs)};

    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: topOrgs.map(o => o.name),
        datasets: [{
          label: 'Involvement Score',
          data: topOrgs.map(o => o.score),
          backgroundColor: 'rgba(102, 126, 234, 0.7)',
          borderColor: 'rgba(102, 126, 234, 1)',
          borderWidth: 1
        }]
      },
      options: {
        indexAxis: 'y',
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: { display: false }
        },
        scales: {
          x: { beginAtZero: true, title: { display: true, text: 'Score' } }
        }
      }
    });
  </script>
</body>
</html>`;
}

/**
 * Write HTML report to temp file and open in default browser
 *
 * @param html - HTML content to write
 * @returns Path to the created report file
 */
export async function openReport(html: string): Promise<string> {
  const filename = `gitsneak-report-${Date.now()}.html`;
  const reportPath = join(tmpdir(), filename);

  await writeFile(reportPath, html, 'utf-8');
  await open(reportPath);

  return reportPath;
}
